In [1]:
import numpy as np

**np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')**

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [5]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [6]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [7]:
np.eye(4,5,dtype=int)#dtype="int32"

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [9]:
np.eye(3,4, k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [6]:
np.eye(3,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(3,3, k=-1)#Start from row 1

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [12]:
np.eye(3,3,k=-2)#Start from row 2

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])