In [13]:
import numpy as np

In [6]:
a1=np.linspace(2.0, 3.0)
a1

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [5]:
len(a1)

50

In [7]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [8]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [9]:
np.linspace(2.0,3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [8]:
np.random.randint(2, size=10)

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1])

In [5]:
x1 = np.random.randint(10,20,15)
x2 = np.random.randint(11,25,15)
x3 = np.random.randint(14,29,15)

In [6]:
arr = np.array([x1,x2,x3])

In [7]:
arr

array([[10, 19, 18, 17, 10, 19, 19, 10, 14, 17, 16, 19, 12, 16, 17],
       [18, 19, 16, 18, 15, 12, 16, 23, 12, 13, 22, 12, 15, 17, 15],
       [18, 25, 16, 14, 20, 15, 15, 17, 21, 28, 17, 27, 16, 22, 24]])

In [10]:
np.random.randint(10,29, size=())

array(18)

In [11]:
np.random.randint(10,29, size=(5,5))

array([[12, 28, 14, 21, 20],
       [12, 17, 11, 26, 20],
       [10, 14, 11, 24, 14],
       [14, 21, 27, 14, 14],
       [12, 26, 22, 15, 13]])

In [12]:
np.random.randint(150,2000, size=(1000,5))

array([[ 859,  720, 1320, 1518,  427],
       [1161,  657,  410,  286, 1981],
       [1841, 1438, 1304,  846,  578],
       ...,
       [ 258, 1930, 1701, 1717, 1341],
       [1157,  765, 1004,  173,  269],
       [1388, 1599, 1394,  853, 1029]])

In [15]:
a=np.random.randint(150,2000, size=(5,5))
a

array([[1364, 1804, 1571,  469,  207],
       [1563,  225, 1593, 1966,  575],
       [1140, 1376,  703, 1060, 1577],
       [1184,  769,  505, 1324,  687],
       [ 418,  667,  546,  560, 1830]])

In [16]:
a[0][3]

469

In [17]:
a[0,3]

469

In [18]:
a[::2, :] #alternate rows and all columns

array([[1364, 1804, 1571,  469,  207],
       [1140, 1376,  703, 1060, 1577],
       [ 418,  667,  546,  560, 1830]])

In [19]:
a[::2, ::2]

array([[1364, 1571,  207],
       [1140,  703, 1577],
       [ 418,  546, 1830]])

In [20]:
a

array([[1364, 1804, 1571,  469,  207],
       [1563,  225, 1593, 1966,  575],
       [1140, 1376,  703, 1060, 1577],
       [1184,  769,  505, 1324,  687],
       [ 418,  667,  546,  560, 1830]])

In [21]:
a[[0,2,3],:]

array([[1364, 1804, 1571,  469,  207],
       [1140, 1376,  703, 1060, 1577],
       [1184,  769,  505, 1324,  687]])

In [22]:
a[[0,2,3],[1,2,4]]

array([1804,  703,  687])